# case_name = ["args", option<grade>]
args-none = [""]
args-many = ["a b c d e f g h i j k l m n o p q r s t u v"]
open-create = [""]
open-rdwr = [""]
open-trunc = [""]
open-many = [""]
read-zero = [""]
read-normal = [""]
write-zero = [""]
write-normal = [""]
close-normal = [""]
exec-once = [""]
exec-multiple = [""]
exec-arg = [""]
wait-simple = [""]
wait-twice = [""]
exit = [""]
halt = [""]
rox-simple = [""]
rox-child = [""]
rox-multichild = ["", 2]
close-stdio = [""]
close-badfd = [""]
close-twice = [""]
read-badfd = [""]
read-stdout = [""]
write-badfd = [""]
write-stdin = [""]
boundary-normal = [""]
boundary-bad = [""]
open-invalid = [""]
sc-bad-sp = [""]
sc-bad-args = [""]
exec-invalid = [""]
wait-badpid = [""]
wait-killed = [""]
bad-load = [""]
bad-store = [""]
bad-jump = [""]
bad-load2 = [""]
bad-store2 = [""]
bad-jump2 = [""]
